name: keepalive

on:
  schedule:
    - cron: "*/30 * * * *"   # roda a cada 10 minutos
  workflow_dispatch:        # permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl app
        run: curl -sS https://mercadolivrecdc.streamlit.app/ > /dev/null
